name: fruit_detection
channels:
  - defaults
  - conda-forge
  - anaconda
  - pytorch
  - nvidia
dependencies:
  - pip=24.0
  - python=3.12.3
  - conda-lock=2.5.6
  - pytorch-lightning=2.1.2
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - torchvision=0.16.1
  - tqdm=4.66.4
  - numpy=1.26.4
  - click=8.1.7
  - scikit-image=0.22.0
  - matplotlib=3.8.4
  - tensorboard=2.12.1
  - rich=13.3.5
  - pip:
      - pytest==8.2.0